DEBUG 2021-02-03 00:09:50.759 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-03 00:09:50.759 UTC: 	 Running on: Linux lxplus758.cern.ch 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-03 00:09:50.759 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-03 00:09:50.760 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mmyllyma/.crab3
INFO 2021-02-03 00:09:50.761 UTC: 	 Will use CRAB configuration file crab_step2_gamma_20k.py
DEBUG 2021-02-03 00:09:50.761 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-03 00:09:50.762 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-03 00:09:50.762 UTC: 	 Working area '/afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/gamma/crab_step2_gamma_20k' already exists 
Please change the requestName in the config file
ERROR 2021-02-03 00:09:50.762 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/gamma/crab_step2_gamma_20k' already exists 
Please change the requestName in the config file
INFO 2021-02-03 00:09:50.768 UTC: 	 Log file is /afs/cern.ch/work/m/mmyllyma/singleParticleResponse/CMSSW_10_4_0/src/PFCalibration/PFChargedHadronAnalyzer/mmylly/gamma/crab.log
